### PR TITLE
Refactor the movies menu to handle missing thumbs

### PR DESCRIPTION
**Pull request by mrsvan**
The movies' menu are blank when any of the listed movies is missing a thumb image or fan art. We add some logic to handle this situation more gracefully.

### CODE REVIEW

**Comment by sharkone** [comment]
Great fix!
Do you mind doing the same fix for TV shows as well? I'll merge and publish a new release after that.

Thanks!

**Comment by sharkone** [comment]
Actually common.py and ServiceCode.pys could also benefit from some extra safety... ;)

**Comment by sharkone** [comment]
You could also use a ternary operator to keep the code cleaner (https://stackoverflow.com/questions/2802726/putting-a-simple-if-then-else-statement-on-one-line)

**Comment by mrsvan** [comment]
Hello Thomas,

Thanks for the quick response.

Python is not my forte, so I will clean up the code with the ternary
operators as suggested.

I'll update the treatment of the thumbs in TV as well, but I have not
encountered many issues with the other code, so I'm not exactly sure where
it would be best to start.

BR,

Stefaan Vanderheyden
+32 484 661888

**Comment by sharkone** [comment]
This pull request is no longer need as I just integrated #121.
Thank you none the less :)

**Pull request closed without merging**
