### PR TITLE
Popcorn API Bug Fixes

### PR DESCRIPTION
**Pull request by spaz926**
* Fixed an issue where consecutive pages after page 1 in TV Shows menu crashes the plugin.
* Updated Popcorn API url to comply with their recent change.
* Updated version to minor release **v1.1.1** 

Fixes issue #83

### CODE REVIEW

**Comment by Deaths-Asylum** [comment]
Good work the patches all seem to work as desired. thank you for the fix. are you able to access other movie sources through the popcorn api as yify seems to be the only source.

**Comment by spaz926** [comment]
Popcorn API uses ExtraTorrent, YTS, and KAT for movies.

Additional sources are not in the scope of this patch. I intend to look into that in the future, but I want to make sure bugs are being taken care of before new features.

@sharkone when/if you approve this pull request and set a new release for v1.1.1 you should think about adding the Bittorrent.bundle.zip to the release so people don't need to change the name of the folder when downloading. Just a thought.

**Comment by Deaths-Asylum** [comment]
Movies are only using yts for me however once you attempt to play in get plex server not working error.

**Comment by spaz926** [comment]
Using https://tv-v2.api-fetch.website/exports/movies I'm only seeing YTS/YIFY as provider. This is a thing with Popcorn API. This plugin directly uses whatever Popcorn API scrapes. Perhaps they are currently only using YTS for movies. 

Regarding your "server not working" error. This happens when you attempt to play the movie? The movie shows up in the list with different formats (720/1080)?

I'm having no issues streaming movies. My plex server is running on macOS. I do not have the ability at the moment to test on other operating systems. What OS are you running on?

**Comment by TehPirat3** [comment]
I'm having streaming issues as well. It happened when I updated Plex. I'm running on Debian Jessie, latest Plex update.

Monitoring network traffic through SSH shows all the peer connections are established and begins to cache. But in browser, it just keeps attempting to play the video to no avail. On devices like Roku and FireTV, it eventually errors out about a playback issue and asks to "Retry" or "Cancel". 

Attempting to play back a file locally is no issue.

**Pull request merged**
